spring:
  application:
    name: spring-security-asymetric-encryption
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/postgres/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  security:

